version: '3.1'
services:
  postgres:
    image: postgres:12-alpine
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=e3i29rse20-r!
      - POSTGRES_USER=postgres
  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=s@finalclass.net
      - PGADMIN_DEFAULT_PASSWORD=fakepassword
 

 
